files:
  # define files included in the analysis (defaults to ["{app,lib}/**/*.rb"])
  included:
    - src/*/*.js*
  # define files excluded from the analysis (defaults to [])
#  excluded:
#    - plugins/vendor/sparkr/sparkr.rb
