language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '4'
before_install:
  - cp $TRAVIS_BUILD_DIR/package.json $TRAVIS_BUILD_DIR/src/package.json
  - cd $TRAVIS_BUILD_DIR/src
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm run semantic-release
  - npm run report:coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
