language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '4'
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - cp $TRAVIS_BUILD_DIR/package.json $TRAVIS_BUILD_DIR/src/package.json
  - mv $TRAVIS_BUILD_DIR/coverage/ $TRAVIS_BUILD_DIR/src/
  - cd $TRAVIS_BUILD_DIR/src
  - npm i semantic-release
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
