language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '4'
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm run semantic-release
  - npm run report:coverage
before_deploy:
  - cp package.json src/
  - cd src
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
