language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '4'
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - cp -r $TRAVIS_BUILD_DIR/src/* $TRAVIS_BUILD_DIR/
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
